name: build and integrate image to Dockerhub
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        user: actions/checkout@v3
      - name: build docker image
        run: |
          docker build -t kooloina/my_python_web_app-web:latest .
      - name: Login to Dockerhub
        user: docker/login-action@v2
        with:
          username: kooloina
          password: tocken 
      - name : push to Docker hube
        run: |
          docker push kooloina/my_python_web_app

